### ISSUE TITLE
Rebooting a deployed cloud launcher instance will format and discard existing data

### ISSUE THREAD

**Issue by boskonyc** [DSPN/google-compute-engine-dse#25]
On a reboot of the cloud launcher compute engine instance, our persistent volumes were formatted. This was unexpected behavior and could easily result in a massive data loss in the wild. 

Here is the line that formats the volumes on boot: https://github.com/DSPN/google-compute-engine-dse/blob/4fe7efea0db3621c969d4ebc1723db7291a652c3/datastax.py#L90

On Oct 26, 2017, a commit changed this line away from using google's safe_format_and_mount script which checks to see if a volume is already formatted before discarding existing data.  (https://github.com/DSPN/google-compute-engine-dse/commit/ed1f100f216d35c5d310485fc2a76cb57eb4177f)

**Comment by gmflau** [comment]
Thanks for reporting the issue.  We will look into that.  However, Google deprecated safe_format_and_mount script from their VM instances a while back.  To reproduce the issue on our end, it would be very helpful if you confirm the following sequence will reproduce the issue you saw:

1. Launch DataStax using GCE Launcher
2. Reboot one of the DSE nodes in GCP VM console

**Comment by gmflau** [comment]
Put in logic to properly handle VM's stop/start and reset scenarios with external storage device.
